### ISSUE TITLE
Can't create directories with special characters from episode names in Windows

### ISSUE THREAD

**Issue by brndn4** [stupied4ever/ruby-tapas-downloader#40]
C:\Users\user>ruby -v
ruby 2.0.0p598 (2014-11-13) [i386-mingw32]

C:\Users\user>gem -v
2.4.8

C:\Users\user>ruby-tapas-downloader download -e user -p pass -d F:\rubytapas\

```
I, [2015-09-23T22:04:14.930305 #15804]  INFO -- : Starting download of episode `336 What Changed?' in `F:\rubytapas\336-what-changed?'...
C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir': Invalid argument - F:\rubytapas\336-what-changed? (Errno::EINVAL)
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/fileutils.rb:203:in `each'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/ruby-tapas-downloader-2.0.3/lib/ruby_tapas_downloader/downloadables/episode.rb:35:in `download'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/ruby-tapas-downloader-2.0.3/lib/ruby_tapas_downloader/downloadables/catalog.rb:20:in `block in download'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/set.rb:232:in `each_key'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/2.0.0/set.rb:232:in `each'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/ruby-tapas-downloader-2.0.3/lib/ruby_tapas_downloader/downloadables/catalog.rb:20:in `download'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/ruby-tapas-downloader-2.0.3/lib/ruby_tapas_downloader/cli.rb:90:in `download_catalog'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/ruby-tapas-downloader-2.0.3/lib/ruby_tapas_downloader/cli.rb:45:in `download'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from C:/RailsInstaller/Ruby2.0.0/lib/ruby/gems/2.0.0/gems/ruby-tapas-downloader-2.0.3/bin/ruby-tapas-downloader:5:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.0.0/bin/ruby-tapas-downloader:23:in `load'
        from C:/RailsInstaller/Ruby2.0.0/bin/ruby-tapas-downloader:23:in `<main>'
```

**Comment by brndn4** [comment]
Hmm, looking at the code on here, it looks like the filename is being sanitized. Not sure why I'm having this issue then. I have version 2.0.3 that I installed with 'gem install ruby-tapas-downloader'.

**Comment by brndn4** [comment]
Turns out the source on rubygems.org is just out of date. I just patched in the new sanitized_title method on my system in lib/ruby_tapas_downloader/downloadables/episode.rb and it worked. Thanks.
