### ISSUE TITLE
Getting Net::HTTPUnauthorized when trying to run

### ISSUE THREAD

**Issue by mattwelke** [stupied4ever/ruby-tapas-downloader#43]
When following the instructions on the main page to use the following command:

```
ruby-tapas-downloader download -e <email> -p <password> -d <download_path>
```

I get the following error message on the console:

```
I, [2017-03-24T16:23:41.143729 #24251]  INFO -- : Logging in...
I, [2017-03-24T16:23:41.502527 #24251]  INFO -- : Fetching episodes feed...
/home/mswelke/.gem/ruby/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:796:in `response_authenticate': 401 => Net::HTTPUnauthorized for https://rubytapas.dpdcart.com/feed -- Basic authentication failed -- available realms: RubyTapas (Mechanize::UnauthorizedError)
	from /home/mswelke/.gem/ruby/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:317:in `fetch'
	from /home/mswelke/.gem/ruby/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:805:in `response_authenticate'
	from /home/mswelke/.gem/ruby/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:317:in `fetch'
	from /home/mswelke/.gem/ruby/2.3.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'
	from /home/mswelke/.gem/ruby/2.3.0/gems/ruby-tapas-downloader-2.0.3/lib/ruby_tapas_downloader/feed_fetcher.rb:27:in `fetch'
	from /home/mswelke/.gem/ruby/2.3.0/gems/ruby-tapas-downloader-2.0.3/lib/ruby_tapas_downloader/cli.rb:82:in `fetch_feed'
	from /home/mswelke/.gem/ruby/2.3.0/gems/ruby-tapas-downloader-2.0.3/lib/ruby_tapas_downloader/cli.rb:43:in `download'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /var/lib/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/mswelke/.gem/ruby/2.3.0/gems/ruby-tapas-downloader-2.0.3/bin/ruby-tapas-downloader:5:in `<top (required)>'
	from /home/mswelke/.gem/ruby/2.3.0/bin/ruby-tapas-downloader:23:in `load'
	from /home/mswelke/.gem/ruby/2.3.0/bin/ruby-tapas-downloader:23:in `<main>'
```

**Comment by pdbradley** [comment]
I get the same.
